[34기 맹주엽] Models.py 작성(ERD 기반)
wecode-bootcamp-korea/34-1st-HDPDB-backend pull request #2
Opened 2022-06-22 08:26 UTC by koceanie

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 설계한 ERD에 기반한 MySQL 데이터 베이스 생성
ERD : https://dbdiagram.io/d/62b2746c69be0b672c164933

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. User 기능을 위한 데이터 베이스 설계
2. products 기능을 위한 데이터 베이스 설계

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데이터베이스의 옵션값들은 앞으로 수정해나가야 할것으로 보임. 

<br />

## :: 기타 질문 및 특이 사항

2022-06-22 08:29 UTC, koceanie commented
필드값이 변할 수 도 있어서 아직 컨벤션 통일은 진행하지 않았습니다.

2022-06-22 08:31 UTC, bigfanoftim requested changes
지금 PR은 models.py만 작성하시고 실제로 이 코드가 데이터베이스에 어떤 영향을 줬을지 전혀 테스트해보지 않고 올라온 PR 같습니다. 
PR을 생성하고 리뷰 라벨을 달기 전에는 항상 본인이 먼저 점검을 해야합니다. 
migrations 파일 생성하시고 데이터베이스에 마이그레이션 해보고 문제가 없는지, 테이블명 컬럼명이 내가 의도한 바가 맞는지 확인 후에 다시 리뷰 요청해주세요.

2022-06-22 08:31 UTC, bigfanoftim commented on HDPDB/products/models.py
> +class Main_Category(models.Model):
class 명에는 언더바(_)를 사용하지 않습니다~
```suggestion
class MainCategory(models.Model):
```

2022-06-23 01:15 UTC, bigfanoftim commented on HDPDB/products/models.py
> +        db_table = 'maincategories'
```suggestion
        db_table = 'main_categories'
```

2022-06-23 01:15 UTC, bigfanoftim commented on HDPDB/products/models.py
> +        db_table = 'subcategories'
```suggestion
        db_table = 'sub_categories'
```

2022-06-23 01:15 UTC, bigfanoftim commented on HDPDB/products/models.py
> +    sub_category_id = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
이 컬럼명은 테이블에 어떻게 들어가있던가요?

2022-06-23 01:48 UTC, koceanie commented on HDPDB/products/models.py
> +    sub_category_id = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
제가 뒤에 아이디 붙는다는걸 까먹고 있었습니다. 이름에서 id값을 삭제하였습니다.

2022-06-23 01:50 UTC, bigfanoftim requested changes
주엽님 바뀐 모델링으로 migration 하시고 다시 올려주세요!

2022-06-23 01:52 UTC, koceanie commented
> 주엽님 바뀐 모델링으로 migration 하시고 다시 올려주세요!
![스크린샷 2022-06-23 오전 10 51 16](https://user-images.githubusercontent.com/104124384/175190365-ea99d6ca-e7cf-4671-83a2-c401b4360999.png)


앗 마이그레이션 하고 테이블 필드값도 확인 하였는데 혹시 반영이 안된부분이 있었나요?

2022-06-23 05:15 UTC, koceanie commented
- 프로덕트 데이터베이스 분리
- discount-product 중간테이블 추가(하나의 이벤트에 다수의 제품 선택 가능하도록함)
- 마이그레이션 초기화후 재생성(FK충돌문제)

2022-06-23 05:29 UTC, bigfanoftim approved these changes
LGTM!

2022-06-23 05:48 UTC, merged