Feature/signinup
wecode-bootcamp-korea/34-1st-HDPDB-backend pull request #3
Opened 2022-06-23 08:39 UTC by koceanie

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 
- 회원가입과 로그인 기능
- 로그인시 엑세스 토큰(jwt)발급

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입시 이메일 정규식과 패스워드 조건에 맞는지 확인(실패시 에러 리턴)
2. 회원가입시에 작성한 이메일값을 기준으로 유저 네임 값 추출 및 저장(ex kocean@xanny.us 입력시 name=kocean)
3. 로그인 성공시 jwt 토큰발급

<br />

## :: 성장 포인트

<br />

## :: 기타 질문 및 특이 사항
- 현재 적용된 정규식은 추후 장고 validation 모듈 혹은 자체 모듈로 대체하여 패스워드 규칙과 추후 입력되는 유저 데이터를 관리할 예정

2022-06-24 04:59 UTC, bigfanoftim requested changes

2022-06-24 04:59 UTC, bigfanoftim commented on HDPDB/core/decorator.py
> +            request.user = user
```suggestion
            request.user = User.objects.get(id=payload['user_id'])
```

2022-06-24 04:59 UTC, bigfanoftim commented on HDPDB/users/views.py
> +            name = email[0:email.index('@')]
이메일의 앞부분만 저장하는 이유가 있을까요?

2022-06-24 04:59 UTC, bigfanoftim commented on HDPDB/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
```python
user = User.objects.get(email = email)

if not User.objects.filter(email=email).exists():
    return JsonResponse({"message": "INVALID_USER"}, status = 401)
```

`get` 메소드를 사용하여 조회했을 때 데이터베이스에 매칭되는 데이터가 없는 경우 python에서 error를 raise 합니다. 그렇기 때문에 `if not User.objects.filter(email=email).exists():` 코드가 실행될 일이 없겠죠?

그러므로 위 if문 코드는 불필요한 코드입니다.

2022-06-24 05:58 UTC, koceanie commented
앗 확인하셨군요. 제가 브런치 관리 실수때문에 현재 브런치로는 sigin, sigup 만 구현한 커밋 부분까지만 마지 요청드릴려고 했는데 다음작업을 브런치 변경없이 진행해버렸습니다 ㅠㅠ signin/signup 부분까지만 다시 요청드리는게 좋을까요? 아님 현재 cart 부분제작중인데 이부분까지 하고 마지요청 드리는게 좋을까요?

2022-06-24 08:26 UTC, bigfanoftim commented
> 앗 확인하셨군요. 제가 브런치 관리 실수때문에 현재 브런치로는 sigin, sigup 만 구현한 커밋 부분까지만 마지 요청드릴려고 했는데 다음작업을 브런치 변경없이 진행해버렸습니다 ㅠㅠ signin/signup 부분까지만 다시 요청드리는게 좋을까요? 아님 현재 cart 부분제작중인데 이부분까지 하고 마지요청 드리는게 좋을까요?

주엽님!! PR 올리실 때는 특별한 이유가 없다면 api 별로 나눠서 올려주세요!! 그래야 리뷰를 해주는 입장에서도 코드를 파악하기 쉽고 히스토리 관리하기에도 용이합니다~!

2022-06-27 06:04 UTC, lordmyshepherd requested changes

2022-06-27 06:04 UTC, lordmyshepherd commented on HDPDB/csv/origin_products.csv
> +• Floating key design
csv 파일은 올라오지 않도록 .gitignore에 추가하시고 다시 올려주세요!

2022-06-27 07:30 UTC, koceanie commented
수정완료 했습니다. 
중간에 이메일의 앞부분을 따로 저장하는 건, 원래 사용자가 온라인상에서 사용하는 닉네임을 따로 받을려고 하였는데 회원가입페이지에 닉네임 입력칸을 구현하지 못해서 우선 이메일의 앞 부분을 따로 저장합니다. 지금은 별로 쓸모없는 부분이긴한데 혹시 추가 기능을 구현하게 되면 사용할 데이터라 추가하였습니다.

2022-06-27 08:32 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-06-27 08:32 UTC, merged